// Generated by CoffeeScript 1.10.0
(function() {
  var assert, category, log_mode, options, seneca;

  assert = require('chai').assert;

  options = {
    test: true
  };

  log_mode = process.env.TEST_LOG_MODE || 'quiet';

  seneca = require('seneca')({
    log: log_mode
  }).use('../category', options);

  category = seneca.pin({
    role: 'category',
    cmd: '*'
  });

  describe('get', function() {
    it('returns category info from datamap', function(done) {
      return category.get({
        id: 'milk'
      }, function(error, category) {
        assert.equal(category.title, 'milk');
        assert.include(category.keyword, 'молоко');
        return done();
      });
    });
    return it('returns null if data was found', function(done) {
      return category.get({
        id: 'abracadabra'
      }, function(error, category) {
        assert.isNull(category);
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=category.test.js.map
