// Generated by CoffeeScript 1.10.0
(function() {
  var assert, log_mode;

  assert = require('chai').assert;

  log_mode = process.env.TEST_LOG_MODE || 'quiet';

}).call(this);

//# sourceMappingURL=cmd.test.js.map
