// Generated by CoffeeScript 1.10.0
(function() {
  var assert, log_mode, options, product, seneca;

  assert = require('chai').assert;

  options = {
    test: true
  };

  log_mode = process.env.TEST_LOG_MODE || 'quiet';

  seneca = require('seneca')({
    log: log_mode
  }).use('../product', options);

  product = seneca.pin({
    role: 'product',
    cmd: '*'
  });

  describe('parse', function() {
    return it('parses product package', function(done) {
      return product.parse({
        title: 'Молоко Great Milk three 1L'
      }, function(error, data) {
        assert.equal(data["package"], '1 l');
        return done();
      });
    });
  });

}).call(this);

//# sourceMappingURL=product.test.js.map
