// Generated by CoffeeScript 1.10.0
(function() {
  var get, path, yaml;

  yaml = require('yamljs');

  path = require('path');

  get = require('./category/get');

  module.exports = function(options) {
    var role, seneca;
    seneca = this;
    role = 'category';
    seneca.add("init:" + role, function(args, respond) {
      var datamap, path_to_datamap;
      path_to_datamap = path.join(__dirname, 'category', 'data.yaml');
      datamap = yaml.load(path_to_datamap);
      options.datamap = datamap;
      return respond();
    });
    seneca.add("role:" + role + ",cmd:get", get(seneca, options));
    return role;
  };

}).call(this);

//# sourceMappingURL=category.js.map
