// Generated by CoffeeScript 1.10.0
(function() {
  var register;

  register = require('./cmd/register');

  module.exports = function(options) {
    var role, seneca;
    seneca = this;
    role = 'price_report';
    seneca.add("role:" + role + ",cmd:register", register(seneca, options));
    return role;
  };

}).call(this);

//# sourceMappingURL=plugin.js.map
