// Generated by CoffeeScript 1.10.0
(function() {
  var PEG, fs, parse, path;

  PEG = require('pegjs');

  path = require('path');

  fs = require('fs');

  parse = require('./product/parse');

  module.exports = function(options) {
    var role, seneca;
    seneca = this;
    role = 'product';
    seneca.add("init:" + role, function(args, respond) {
      var grammar, path_to_grammar;
      path_to_grammar = path.join(__dirname, 'product', 'PTP.peg');
      grammar = fs.readFileSync(path_to_grammar, {
        encoding: 'utf-8'
      });
      options.parser = PEG.buildParser(grammar);
      return respond();
    });
    seneca.add("role:" + role + ",cmd:parse", parse(seneca, options));
    return role;
  };

}).call(this);

//# sourceMappingURL=product.js.map
