// Generated by CoffeeScript 1.10.0
(function() {
  var traverse, validator;

  traverse = require('traverse');

  validator = require('validator');

  module.exports = function(seneca, options) {
    var cmd_get;
    cmd_get = function(msg, respond) {
      var datamap, id, result;
      datamap = options.datamap;
      id = validator.trim(msg.id.toLowerCase());
      result = null;
      traverse(datamap).forEach(function(node_value) {
        var node;
        node = this;
        if (node.key === id) {
          return result = node_value;
        }
      });
      return respond(null, result);
    };
    return cmd_get;
  };

}).call(this);

//# sourceMappingURL=get.js.map
