// Generated by CoffeeScript 1.10.0
(function() {
  var validator;

  validator = require('validator');

  module.exports = function(seneca, options) {
    var cmd_parse;
    cmd_parse = function(args, respond) {
      var i, len, object, objects, parser, result, title;
      parser = options.parser;
      title = validator.trim(args.title.toLowerCase());
      objects = parser.parse(title);
      result = {
        origin: args.title,
        words: []
      };
      for (i = 0, len = objects.length; i < len; i++) {
        object = objects[i];
        if ('word' in object) {
          result.words.push(object.word);
        }
        if ('package' in object) {
          result["package"] = object["package"];
        }
        if ('percentage' in object) {
          result.percentage = object.percentage;
        }
      }
      result.title = result.words.join(' ');
      return respond(null, result);
    };
    return cmd_parse;
  };

}).call(this);

//# sourceMappingURL=parse.js.map
