// Generated by CoffeeScript 1.10.0
(function() {
  var PEG, fs, path;

  PEG = require('pegjs');

  fs = require('fs');

  path = require('path');

  module.exports = function(seneca, options) {
    var cmd_parse;
    cmd_parse = function(args, respond) {
      var grammar, parser, path_to_grammar, result;
      path_to_grammar = path.join(__dirname, 'PTP.peg');
      grammar = fs.readFileSync(path_to_grammar, {
        encoding: 'utf-8'
      });
      parser = PEG.buildParser(grammar);
      result = parser.parse(args.title);
      return respond(null, result);
    };
    return cmd_parse;
  };

}).call(this);

//# sourceMappingURL=parse.js.map
